### ISSUE TITLE
[Feature] Allow using any OpenAI-compatible mode

### ISSUE THREAD

**Issue by arsaboo** [virattt/ai-hedge-fund#13]
Currently, the `model="gpt-4o"` is hardcoded in the code. We should allow using any OpenAI-compatible model. This will allow users to use other providers (e.g., OpenRouter) and even local models.

**Comment by jacks-sam1010** [comment]
Hello, we tried to solve the issue.

This is what we did:

Modified the code to allow using any OpenAI-compatible model instead of hardcoding 'gpt-4o'. Added a command-line argument to specify the model and updated the LLM initialization.

You can review changes in this commit: https://github.com/jacks-sam1010/virattt-ai-hedge-fund-13/commit/929196a08705d05fa2ed0faf120d8c8354635df5.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

Latta AI seeks to solve problems in open source projects as part of its mission to support developers around the world. Learn more about our mission at https://latta.ai/ourmission . If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by arsaboo** [comment]
@jacks-sam1010 Can you create a PR with those changes? Instead of (or in addition to) using CLI to specify the model, we should use the .env file.

**Comment by virattt** [comment]
Yes, please create a PR 👍

**Comment by arsaboo** [comment]
@virattt  let's keep the issue open until a PR is submitted.
