### ISSUE TITLE
Request - financialdatasets.ai request type and frequency

### ISSUE THREAD

**Issue by blaudp79** [virattt/ai-hedge-fund#17]
Hi,

Can you please update the readme file with financialdatasets.ai request type needed for proper operation and also the number of times the request is run after running the script?

Prices $0.01 / request
Options $0.02 / request
Financial metrics $0.02 / request
Insider trades $0.02 / request
Institutional ownership $0.02 / request
SEC filings $0.02 / request
Segmented revenue $0.02 / request
Income statements $0.04 / request
Balance sheets $0.04 / request
Cash flow statements $0.04 / request
All financial statements $0.10 / request
Search $0.01 per 10 filters

Thanks.

**Comment by virattt** [comment]
Hi @blaudp79 - I am hesitant to add the pricing to the README of this project, because whenever I update the pricing of the API, I will have to remember to update this README.

Instead, we can add a link in the README to the pricing page of the API, which is here https://www.financialdatasets.ai/pricing

Please feel free to put up a pull request with this change 🙏
